# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "40a9bbba818cecfd58dfaf2dec309fbd"
name = "seal-app-dev"
application_url = "https://insert-launched-fate-desk.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-for-extensibility.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://insert-launched-fate-desk.trycloudflare.com/auth/callback",
  "https://insert-launched-fate-desk.trycloudflare.com/auth/shopify/callback",
  "https://insert-launched-fate-desk.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
